default:
  image:
    name: mysql:latest
    entrypoint: ["/usr/bin/env"]

  before_script:
    - apt -y update
    - apt -y install apt-utils wget
    - wget https://pascalroeleven.nl/deb-pascalroeleven.gpg
    - apt-key add deb-pascalroeleven.gpg
    - echo "deb http://deb.pascalroeleven.nl/python3.8 buster-backports main" >> /etc/apt/sources.list
    - apt -y install net-tools python3.8 python3.8-venv python3.8-dev
    - apt -y upgrade


django-tests:
  stage: test

  variables:
    MYSQL_DATABASE: django
    MYSQL_ROOT_PASSWORD: root 

  script:
    - cd src/
    - python3.8 -m venv venv
    - . venv/bin/activate
    - pip3 install -r requirements.txt
    - python3 development-manage.py jenkins --enable-coverage --coverage-rcfile=.coveragerc

  artifacts:
    reports:
      cobertura: src/reports/coverage.xml
      junit: src/reports/junit.xml


code-quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
    SP_VERSION: 0.85.26
  allow_failure: true
  services:
    - docker:stable-dind
  before_script: []
  script:
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/ci-cd/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json


flake8:
  script:
    - pip3 install flake8-gl-codeclimate
    - flake8 --exit-zero --format gl-codeclimate --output-file gl-code-quality-report.json src/
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
