version: '3'

services:
  django:
    build:
      dockerfile: ./docker/gwcloud_db_search.Dockerfile
      context: .
    image: nexus.gw-cloud.org/docker/gwcloud_db_search:0.1
    container_name: gwcloud_db_search
    ports:
      - "8000"
