apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: vault-agent
    app.kubernetes.io/instance: db-search 
  name: secrets-integrator-db-search
  namespace: gwcloud
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      labels:
        app: vault-kube-integrator
    spec:
      backoffLimit: 1
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-init-first: 'true'
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/agent-inject-secret-db-search.yaml: kv/gwcloud/db-search
            vault.hashicorp.com/agent-inject-template-db-search.yaml: |
              {{- with secret "kv/gwcloud/db-search" -}}
              apiVersion: v1
              kind: Secret
              type: Opaque
              stringData:
                {{ range $k, $v := .Data }}
                {{ $k }}: {{ $v }}
                {{ end }}
              metadata:
                namespace: gwcloud
                name: db-search 
              {{- end }}
            vault.hashicorp.com/agent-pre-populate-only: 'true'
            vault.hashicorp.com/role: db-search 
        spec:
          containers:
            - command:
                - kubectl
                - apply
                - '-f'
                - /vault/secrets/
              image: 'bitnami/kubectl:1.17.4'
              imagePullPolicy: IfNotPresent
              name: db-search-vault-kube-integrator
              resources: {}
          imagePullSecrets:
            - name: regcred
          restartPolicy: Never
          serviceAccountName: db-search 
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 1
