---
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gwcloud-db-search
  namespace: gwcloud
  labels:
    name: gwcloud-db-search
spec:
  replicas: 1
  selector:
    matchLabels:
        name: gwcloud-db-search
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        name: gwcloud-db-search
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: db-search
            - secretRef:
                name: common
          name: gwcloud-db-search
          image: nexus.gwdc.org.au/docker/gwcloud_db_search:0.4
          ports:
            - name: http
              containerPort: 8000
          resources: {}
          tty: true
      imagePullSecrets:
      - name: regcred
... 
