---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-integrator-db-search
  namespace: gwcloud
  labels:
    app: vault-agent
spec:
  selector:
    matchLabels:
      app: vault-kube-integrator
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject-secret-env: "gwcloud/kv/db-search"
        vault.hashicorp.com/agent-inject-template-env: |
          {{- with secret "gwcloud/kv/db-search" -}}
          ---
          apiVersion: v1
          kind: Secret
          metadata:
            name: db-search
          type: Opaque
          stringData:
            {{ range $k, $v := .Data.data }}
            {{ $k }}: {{ $v }}
            {{ end }}
          ...
          {{- end }}
        vault.hashicorp.com/role: "gwcloud"
      labels:
        app: vault-kube-integrator
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 0
      serviceAccountName: gwcloud
      containers:
      - name: app
        image: bitnami/kubectl:1.17.4
        command: ["bash"]
        livenessProbe:
          exec:
            command:
            - kubectl
            - apply
            - -f
            - /vault/secrets/env
          initialDelaySeconds: 5
          periodSeconds: 5
        tty: true
        volumeMounts:
          - mountPath: /.kube
            name: secrets
      nodeSelector:
        dedicated: master
      volumes:
        - name: secrets
          hostPath:
            path: /home/ubuntu/.kube
            type: Directory
...