apiVersion: v1
kind: Service
metadata:
  labels:
    name: gwcloud-db-search
  name: gwcloud-db-search
  namespace: gwcloud
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    name: gwcloud-db-search
  sessionAffinity: None
  type: ClusterIP
