---
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gwcloud-db-search-nginx
  namespace: gwcloud
  labels:
    name: gwcloud-db-search-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
        name: gwcloud-db-search-nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        name: gwcloud-db-search-nginx
    spec:
      containers:
        - name: gwcloud-db-search-nginx
          image: nexus.gw-cloud.org/docker/gwcloud_db_search_nginx:0.1
          ports:
            - name: http
              containerPort: 8000
          resources: {}
          tty: true
      imagePullSecrets:
      - name: regcred
... 
