---
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gwcloud-db-search-django
  namespace: gwcloud
  labels:
    name: gwcloud-db-search-django
spec:
  replicas: 1
  selector:
    matchLabels:
        name: gwcloud-db-search-django
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        name: gwcloud-db-search-django
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: db-search
            - secretRef:
                name: common
          name: gwcloud-db-search-django
          image: nexus.gw-cloud.org/docker/gwcloud_db_search_django:0.1
          ports:
            - name: http
              containerPort: 8000
          resources: {}
          tty: true
      imagePullSecrets:
      - name: regcred
... 
