
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: vault-agent
  name: db-search-role
rules:
  - apiGroups: ["*"]
    #
    # at the HTTP level, the name of the resource for accessing Secret
    # objects is "secrets"
    resources: ["secrets"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: db-search-rolebinding
  labels:
    app: vault-agent
subjects:
  - kind: ServiceAccount
    name: db-search 
    namespace: gwcloud
roleRef:
  kind: Role
  name: db-search-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-search 
  namespace: gwcloud
